import dns from 'node:dns/promises';
import net from 'node:net';

const ROOT_ID = '1q8fnN4-WYFlbGXUkRAWj8uqudNBW4qG0';
const SCOPES = {
  '01_KNOWLEDGE':'1ccp9ieYigI46M38_be9oRWKoG7wycjO3',
  '02_APPROVED':'10Sfb2I0xwYMWr_uOupf-8ciWH3C3RoI1',
  '03_TEMPLATES':'1Uj27l43MhVOTx--AkxP0Vs2V3OTOWi5j',
  '04_SKILLS':'1V9XAIHC7N246XB2OCNKazeKpFqNafgaO',
  '05_TRAINING':'1UUndKlNOLoQ6Cww7xKLP1eErxkTUpiTS',
  '06_OUTPUTS':'17bXsKroYm0Jns0s8Qs6R49N4tfTw6BEh'
};
const ALLOWED_ACTIONS = new Set(['health','search','read','list']);

function json(res,status,body){res.setHeader('cache-control','no-store');res.setHeader('x-content-type-options','nosniff');return res.status(status).json(body)}
function clean(input,max=12000){return String(input??'').replace(/\0/g,'').trim().slice(0,max)}
function stripMarkup(input){return String(input??'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/\s+/g,' ').trim()}
function isPrivateIp(ip){if(net.isIPv4(ip)){const p=ip.split('.').map(Number);return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)}if(net.isIPv6(ip)){const v=ip.toLowerCase();return v==='::1'||v.startsWith('fc')||v.startsWith('fd')||v.startsWith('fe80:')}return true}
async function publicHttpsUrl(raw){const u=new URL(raw);if(u.protocol!=='https:')throw new Error('HTTPS_REQUIRED');if(u.username||u.password)throw new Error('URL_CREDENTIALS_FORBIDDEN');const host=u.hostname.toLowerCase();if(host==='localhost'||host.endsWith('.local'))throw new Error('PRIVATE_HOST_FORBIDDEN');const answers=await dns.lookup(host,{all:true,verbatim:true});if(!answers.length||answers.some(a=>isPrivateIp(a.address)))throw new Error('PRIVATE_IP_FORBIDDEN');return u}
function sanitizeScopes(input){const requested=Array.isArray(input)?input:[];const names=requested.filter(x=>Object.prototype.hasOwnProperty.call(SCOPES,String(x))).slice(0,6);return names.length?names:['02_APPROVED','01_KNOWLEDGE']}
function approvalFor(source){const scope=String(source?.scope||'');if(scope==='02_APPROVED')return'approved';if(scope==='03_TEMPLATES')return String(source?.approvalState||'').toLowerCase()==='approved'?'approved':'reference';if(scope==='04_SKILLS')return String(source?.approvalState||'').toLowerCase()==='approved'?'approved':'draft';return String(source?.approvalState||'reference')}
function sanitizeSources(data){return (Array.isArray(data?.sources)?data.sources:[]).slice(0,20).map(s=>({kind:clean(s?.kind,80)||'drive',scope:clean(s?.scope,40),source:clean(s?.source,220)||`Drive · ${clean(s?.title,180)}`,title:clean(s?.title,220)||'Tài liệu Drive',url:clean(s?.url,2048),domain:'drive.google.com',text:stripMarkup(s?.text||s?.snippet||'').slice(0,20000),approvalState:approvalFor(s),provenance:{fileId:clean(s?.fileId||s?.id,180),scope:clean(s?.scope,40),modifiedTime:clean(s?.modifiedTime,80),revision:clean(s?.revision,180),mimeType:clean(s?.mimeType,180)}})).filter(s=>s.title||s.text)}

async function callBridge(action,body){const raw=process.env.DRIVE_BRAIN_BRIDGE_URL||'',token=process.env.DRIVE_BRAIN_TOKEN||'';if(!raw||!token)return{configured:false,reason:!raw?'DRIVE_BRAIN_BRIDGE_URL_MISSING':'DRIVE_BRAIN_TOKEN_MISSING'};const url=await publicHttpsUrl(raw);const payload={token,action,rootId:ROOT_ID,scopes:Object.fromEntries(body.scopes.map(name=>[name,SCOPES[name]])),query:clean(body.query,1600),fileId:clean(body.fileId,180),limit:Math.min(20,Math.max(1,Number(body.limit)||8))};const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json','user-agent':'AI-Office-Drive-Brain/2.0'},body:JSON.stringify(payload),redirect:'follow',signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error(`BRIDGE_${response.status}`);const data=await response.json();if(data?.ok===false)throw new Error(clean(data?.error,120)||'BRIDGE_REJECTED');return{configured:true,data}}

export default async function handler(req,res){if(req.method!=='POST')return json(res,405,{error:'METHOD_NOT_ALLOWED'});const action=clean(req.body?.action,40).toLowerCase()||'health';if(!ALLOWED_ACTIONS.has(action))return json(res,400,{error:'INVALID_ACTION',allowed:[...ALLOWED_ACTIONS]});const scopes=sanitizeScopes(req.body?.scopes);try{const result=await callBridge(action,{scopes,query:req.body?.query,fileId:req.body?.fileId,limit:req.body?.limit});if(!result.configured)return json(res,200,{configured:false,live:true,rootId:ROOT_ID,scopes,reason:result.reason,required:['DRIVE_BRAIN_BRIDGE_URL','DRIVE_BRAIN_TOKEN']});const data=result.data||{};if(action==='health')return json(res,200,{configured:true,live:true,provider:'google-drive-bridge',rootId:ROOT_ID,scopes:Object.keys(SCOPES),bridgeHealth:data?.health||'ok'});if(action==='search'||action==='list'){const sources=sanitizeSources(data);return json(res,200,{configured:true,live:true,provider:'google-drive-bridge',sources,count:sources.length})}if(action==='read'){const sources=sanitizeSources({sources:data?.source?[data.source]:(data?.sources||[])});return json(res,200,{configured:true,live:true,provider:'google-drive-bridge',source:sources[0]||null})}return json(res,400,{error:'INVALID_ACTION'})}catch(error){console.error('drive_brain_v20_error',{action,message:String(error?.message||error).slice(0,220)});return json(res,502,{configured:Boolean(process.env.DRIVE_BRAIN_BRIDGE_URL&&process.env.DRIVE_BRAIN_TOKEN),error:'DRIVE_BRIDGE_FAILED'})}}
